---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: eda-playground-ocp

namespace: eda-playground

resources:
  - ../base
  - route.yaml

labels:
  - pairs:
      app.kubernetes.io/instance: eda-playground
      app.kubernetes.io/version: "1.0.0"
      app.kubernetes.io/platform: openshift

# Optionally override image tag
# images:
#   - name: ghcr.io/bbgrimmett2/eda-playground
#     newTag: v1.0.0
